---
stages:
  - syntax
  - unit
  - acceptance
  - release

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
  - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.5.1-Puppet ~> 5.0:
  stage: 'syntax'
  image: 'ruby:2.5.1'
  script:
    - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 5.0'

parallel_spec-Ruby 2.5.1-Puppet ~> 5.0:
  stage: 'unit'
  image: 'ruby:2.5.1'
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 5.0'

acceptance with Puppet5 Ubuntu1804:
  stage: 'acceptance'
  variables:
    RBENV_VERSION: '2.5.1'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_IS_PE: 'no'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    BEAKER_debug: 'true'
    BEAKER_setfile: 'ubuntu1804-64'
    BEAKER_HYPERVISOR: 'docker'
  script:
    - bundle exec rake beaker
  tags:
    - puppet-tests

module release:
  stage: 'release'
  variables:
    RBENV_VERSION: '2.5.1'
  script:
    - pdk build
  tags:
    - puppet-tests
  only:
    - tags
  except:
    - branches
  artifacts:
    paths:
      - pkg/
    expire_in: '6 weeks'

